spring.application.name=urlshortener

#spring.data.mongodb.uri=mongodb://localhost:27017/url_shortener

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

#SPRING_DATA_MONGODB_URI=mongodb+srv://pspatil:mniPspiwtbiG4E@cluster0.xxxxx.mongodb.net/urlshortener?retryWrites=true&w=majority