spring.application.name=urlshortener

#spring.data.mongodb.uri=mongodb://localhost:27017/url_shortener

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

#spring.data.mongodb.uri=mongodb+srv://pspatil:mniPspiwtbiG4E@cluster0.xu7xqyn.mongodb.net/urlshortener?retryWrites=true&w=majority

#spring.data.redis.host=clear-cricket-133680.upstash.io
#spring.data.redis.port=6379
#spring.data.redis.password=gQAAAAAAAgowAAIgcDE3M2E1NzU3YmM1YTU0Y2EzOWUxNDk5MzI1ZTI2ZDE2Yw
#spring.data.redis.ssl.enabled=true

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true