spring.application.name=urlshortener


#------------ Local Environment ------------------------


#------------ Production Environment ------------------------
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
spring.jackson.serialization.write-dates-as-timestamps=false
spring.rabbitmq.addresses=${RABBITMQ_URL}

